export const FETCH_INVESTMENT_RECORD = 'SET_INVESTMENT_RECORD';
export const SET_FAILURE_INVESTMENT_RECORD = 'SET_FAILURE_INVESTMENT_RECORD';
export const SET_INVESTMENT_RECORD = 'SET_INVESTMENT_RECORD';
