export const SET_FAILURE = 'SET_FAILURE';

export const FETCH_INVESTMENT_RECORD = 'FETCH_INVESTMENT_RECORD';
export const SET_INVESTMENT_RECORD = 'SET_INVESTMENT_RECORD';
export const SET_FILTER_INVESTMENT_RECORD = 'SET_FILTER_INVESTMENT_RECORD';
